'use client';

import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import type { GenerateClinicalReportOutput } from "@/ai/flows/generate-clinical-report";
import { FileText, Lightbulb, ListChecks, TestTube, AlertTriangle } from "lucide-react";

interface AiReportDisplayProps {
  report: GenerateClinicalReportOutput;
}

export function AiReportDisplay({ report }: AiReportDisplayProps) {
  return (
    <Card className="bg-accent/20 border-accent">
      <CardHeader>
        <CardTitle>AI-Generated Clinical Report</CardTitle>
        <CardDescription>This report was generated by CareVision AI. Please verify all findings.</CardDescription>
      </CardHeader>
      <CardContent className="space-y-6">
        <div>
          <h3 className="font-semibold mb-2 flex items-center"><FileText className="mr-2 h-5 w-5 text-primary" /> Summary</h3>
          <p className="text-sm text-muted-foreground">{report.summary}</p>
        </div>

        {report.red_flags && report.red_flags.length > 0 && (
          <div>
            <h3 className="font-semibold mb-2 flex items-center text-destructive"><AlertTriangle className="mr-2 h-5 w-5" /> Red Flags</h3>
            <ul className="space-y-1 list-disc list-inside">
              {report.red_flags.map((flag, index) => (
                <li key={index} className="text-sm text-destructive">{flag}</li>
              ))}
            </ul>
          </div>
        )}

        <div className="grid md:grid-cols-2 gap-6">
            <div>
                <h3 className="font-semibold mb-2 flex items-center"><Lightbulb className="mr-2 h-5 w-5 text-primary" /> Key Findings</h3>
                <ul className="space-y-2">
                {report.key_findings.map((finding, index) => (
                    <li key={index} className="text-sm flex items-start">
                        <span className="text-primary mr-2 mt-1">&#8226;</span>
                        {finding}
                    </li>
                ))}
                </ul>
            </div>
            <div>
                <h3 className="font-semibold mb-2 flex items-center"><TestTube className="mr-2 h-5 w-5 text-primary" /> Recommended Tests</h3>
                <div className="flex flex-wrap gap-2">
                {report.recommended_tests.map((test, index) => (
                    <Badge key={index} variant="secondary">{test}</Badge>
                ))}
                </div>
            </div>
        </div>

        <div>
          <h3 className="font-semibold mb-2 flex items-center"><ListChecks className="mr-2 h-5 w-5 text-primary" /> Likely Diagnoses</h3>
          <div className="space-y-3">
            {report.likely_diagnoses.map((diag, index) => (
              <div key={index} className="p-3 rounded-md border bg-background/50">
                <p className="font-medium text-sm">{index + 1}. {diag.diagnosis}</p>
                <p className="text-xs text-muted-foreground mt-1"><strong>Reasoning:</strong> {diag.reason}</p>
              </div>
            ))}
          </div>
        </div>

      </CardContent>
    </Card>
  );
}
